

let Champions = [
    {
      img : process.env.PUBLIC_URL + 'champion/Gangplank.jpg',
      name : "갱플랭크",
      cost : 1,
      line : "우세",
      job : ["결투가"],
      attack_range : 1,
      skill : "불의 심판",
      mana : "0/50",
      skill_effect : ["갱플랭크가 대상에게 불타는 총알을 발사합니다. 총알에 맞은 적은 마법 피해를 입고 8초동안 33%의 상처를 입습니다."],
      demage : ["피해량 : 230 / 345 / 515"],
    },
  
    {
      img : process.env.PUBLIC_URL + 'champion/Garen.png',
      name : "가렌",
      cost : 4,
      line : "메카:프라임",
      job : ["엄호대"],
      attack_range : 1,
      skill : "메카의 응징",
      mana : "100/180",
      skill_effect : ["가렌이 주변 적 하나에게 검을 내리쳐 2칸 이내의 적에게 물리 피해를 입히고 1.75초 동안 기절시킵니다."],
      demage : ["피해량 : 60 / 90 / 200"],
    },
  
    {
      img : process.env.PUBLIC_URL + 'champion/EzrealFuture.png',
      name : "궁극의 이즈리얼",
      cost : 5,
      line : "무한대팀",
      job : ["평행세계", "특등사수"],
      attack_range : 4,
      skill : "대체 현실의 이즈리얼",
      mana : "50/150",
      skill_effect : ["이즈리얼이 시간대를 부수고 시간의 복제 5명을 불러와 가장 큰 적 무리에게 에너지 구체를 발사합니다. 구체에 맞은 적은 물리 피해를 입습니다."],
      demage : ["공격력 비례 피해 : 133% / 133% / 277%"],
    },

    {
      img : process.env.PUBLIC_URL + 'champion/Gnar.png',
      name : "나르",
      cost : 3,
      line : "기계유망주",
      job : ["익살꾼"],
      attack_range : 1,
      skill : "로봇의 분노",
      mana : "20/80",
      skill_effect : ["나르가 주변을 베어 적중한 적들에게 물리 피해를 입힙니다. 나르의 현재 대상에게 300%의 피해를 입히며, 스킬이 치명타로 적용됩니다."],
      demage : ["범위 가르기 기본 피해량 : 20 / 30 / 50"],
    },
    
    {
      img : process.env.PUBLIC_URL + 'champion/Nunu.jpg',
      name : "누누",
      cost : 5,
      line : "기계유망주",
      job : ["마스코트"],
      attack_range : 1,
      skill : "데굴데굴 로봇공!",
      mana : "마나: 0/90",
      skill_effect : ["기본 지속 효과: 누누와 윌럼프가 천천히 결투장에서 가장 멀리 있는 적을 향해 공을 굴립니다. 공은 통과하는 모든 적에게 잠시 기절시키고 마법 피해를 입힙니다. 대상에 도달하면 새로운 목적지를 찾습니다. 누누와 윌럼프가 초당 마나를 30 얻습니다.","사용 시: 누누와 윌럼프가 공의 크기를 키우며 이동 속도를 붙입니다. 공의 크기와 피해량이 40%% 증가합니다."],
      demage : ["피해량 : 120 / 180 / 2000"],
    },

    {
      img : process.env.PUBLIC_URL + 'champion/Nasus.jpg',
      name : "나서스",
      cost : 1,
      line : "동물특공대",
      job : ["마스코트"],
      attack_range : 1,
      skill : "꽁!",
      mana : "0/60",
      skill_effect : ["나서스가 대상에게 지팡이를 휘둘러 물리 피해를 입히고, 3초 동안 40%의 동상을 겁니다."],
      demage : ["추가 피해량 : 60 / 90 / 135"],
    },

    {
      img : process.env.PUBLIC_URL + 'champion/Neeko.png',
      name : "니코",
      cost : 4,
      line : "별수호자",
      job : ["주문투척자"],
      attack_range : 4,
      skill : "폴짝 만개",
      mana : "0/80",
      skill_effect : ["니코가 대상을 향해 개구리를 던집니다. 개구리는 가장 가까운 적에게 3번 도약하며 반경 안의 적들에게 각각 피해를 입힙니다. 마지막 도약은 강화되어 더 넓은 반경 안의 적들에게 마법 피해를 입힙니다."],
      demage : ["피해량 : 75 / 110 / 300"],
    },

    {
      img : process.env.PUBLIC_URL + 'champion/Nilah.jpg',
      name : "닐라",
      cost : 3,
      line : "별수호자",
      job : ["격투가"],
      attack_range : 1,
      skill : "환희",
      mana : "50/125",
      skill_effect : ["닐라가 칼날 채찍을 휘둘러 주변의 적들에게 피해를 입히고, 자신과 아군의 체력을 1초 동안 회복시킵니다. 마무리로 마법 피해를 입힙니다."],
      demage : ["회복량 : 250 / 300 / 400","피해량 : 90 / 135 / 225"],
    },

    {
      img : process.env.PUBLIC_URL + 'champion/Draven.jpg',
      name : "드레이븐",
      cost : 2,
      line : "메카:프라임",
      job : ["에이스"],
      attack_range : 4,
      skill : "죽음의 소용돌이",
      mana : "70/140",
      skill_effect : ["드레이븐이 대상을 향해 두 개의 거대한 도끼를 던져 경로상의 모든 적에게 물리 피해를 입힙니다. 도끼의 피해량은 적에게 닿을 때마다 25%씩 감소합니다. 도끼는 드레이븐에게 돌아옵니다."],
      demage : ["피해량 : 60 / 95 / 145"],
    },

    {
      img : process.env.PUBLIC_URL + 'champion/Rammus.jpg',
      name : "람머스",
      cost : 3,
      line : "위협",
      job : [""],
      attack_range : 1,
      skill : "모래 폭격",
      mana : "70/140",
      skill_effect : ["기본 지속 효과: 추가 방어력 획득", "사용 시: 람머스가 힘차게 뛰어올라 가장 큰 적 무리에게 돌진하며 마법 피해를 입히고 1.25초 동안 공중에 띄웁니다. 그리고 4초 동안 적들의 공격력을 40% 감소시킵니다."],
      demage : ["방어력 : 60 / 90 / 150", "방어력 비례 피해 : 150% / 175% / 204%", "추가 피해량 : 30 / 50 / 80"],
    },

    {
      img : process.env.PUBLIC_URL + 'champion/Lux.jpg',
      name : "럭스",
      cost : 1,
      line : "별수호자",
      job : ["주문투척자"],
      attack_range : 4,
      skill : "광휘의 특이점",
      mana : "0/70",
      skill_effect : ["럭스가 대상을 향해 빛의 구체를 날립니다. 구체는 폭발하며 대상의 공격력을 4초 동안 40% 감소시키고 주변 적들에게 피해를 입힙니다."],
      demage : ["피해량 : 220 / 330 / 500"],
    },

    {
      img : process.env.PUBLIC_URL + 'champion/Renekton.jpg',
      name : "레넥톤",
      cost : 1,
      line : "레이저단",
      job : ["싸움꾼"],
      attack_range : 1,
      skill : "강신",
      mana : "0/50",
      skill_effect : ["레넥톤이 8초 동안 자신의 신체를 강화해 최대 체력이 증가하고 기본 공격 시 자신 최대 체력 5%만큼 추가 마법 피해를 입힙니다."],
      demage : ["체력 증가량 : 200 / 250 / 300"],
    },

  ] 

export default Champions;